import time

from pydantic_ai import Agent, RunContext
from pydantic_ai.models.ollama import OllamaModel
from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.output import NativeOutput
from pydantic_ai.providers.ollama import OllamaProvider
from pydantic import BaseModel, Field, ValidationError

from typing import List, Optional
from vector_db5 import *

u_prompt=""""
Fattura 1(2)
Numero di fattura Data fattura
51 2026-03-19
NEON LUX PUBBLICITA' SRL
Indirizzo cliente
MASCOT INTERNATIONAL ITALY SRL
VIA DELL'ARTIGIANATO SNC
IT 24046 OSIO SOTTO
BG
Vostra partita IVA IT10041780965
Vostro Codice fiscale 10041780965
Numero Documento di
trasporto
29
Scadenza Pagamento 2026-03-19
Metodo di pagamento Bonifico
Numero Numero di
articolo
Descrizione Quantità Unità Prezzo unit. Aliquota d'Imposta Importo netto
1 ** Rif. Preventivo 390 del
20/12/2024 Rif. Conferma
d'ordine 14 del 26/02/2025
Rif. Fattura 39/25 del
28/02/2025
0,00 22,00 % 0,00 EUR
2 ** Rif. Doc. di trasporto 29
del 16/03/2026:
0,00 22,00 % 0,00 EUR
3 **RIF. NS SCHEDA NR.
326/24
0,00 22,00 % 0,00 EUR
5 INSEGNA D'ESERCIZIO
"LETTERE SCATOLATE
LUMINOSE LUCE
INDIRETTA A LED" così
realizzata: - Lettere
scatolate in alluminio
fronte chiuso - Agganci
per fissaggio a parete
- Verniciatura a forno
(colore a scelta da
cartella RAL) - Impianto
di illuminazione a led
completo di alimentatori
ed accessori - Materiale di
consumo ed accessori vari
- dimensione cm 1650x125
1,00 NR 15 000,00 22,00 % 15 000,00 EUR
7 INSTALLAZIONE E SPESE
VARIE - (manodopera,
spese viaggio, trasporto e
varie)
1,00 NR 2 015,00 22,00 % 2 015,00 EUR
9 PRATICA COMUNE (escluso
spese bolli e diritti di
segreteria)
1,00 NR 200,00 22,00 % 200,00 EUR
11 MARCHE DA BOLLO 2,00 NR 16,00 0,00 % 32,00 EUR
13 DIRITTI DI SEGRETERIA 1,00 NR 53,00 0,00 % 53,00 EUR
NEON LUX PUBBLICITA' SRL
VIA BORGO PALAZZO 102
IT 24125 Bergamo
BG
035214119
info@neonluxbergamo.it
Partita IVA
IT03624680165
Codice fiscale
03624680165
Numero REA
03624680165
IBAN
IT37U0503411102000000020624
Generated by
Fattura 2(2)
Numero di fattura Data fattura
51 2026-03-19
Numero Numero di
articolo
Descrizione Quantità Unità Prezzo unit. Aliquota d'Imposta Importo netto
15 PRATICA AUTOSTRADA
(escluso spese bolli e
diritti di segreteria)
1,00 NR 200,00 22,00 % 200,00 EUR
17 FIRME PER
AUTOCERTIFICAZIONE
PAESAGGISTICA E
STABILITA' DA TECNICO
ABILITATO
1,00 NR 400,00 22,00 % 400,00 EUR
19 COLLEGAMENTO
ELETTRICO E IMPIANTO
ELETTRICO ALLACCIATO
SU VOSTRA LINEA
ESTERNA EFFETTUATO DA
NOSTRO ELETTRICISTA
QUALIFICATO
1,00 NR 400,00 22,00 % 400,00 EUR
21 ELABORAZIONE GRAFICA 1,00 NR 200,00 22,00 % 200,00 EUR
23 Acconto (Rif. Fattura 39 del
28/02/2025)
-9 242,34 22,00 % -9 242,34 EUR
25 COORDINATE BANCARIE:
BANCO BPM SPA FILIALE
DI BERGAMO AG. 2
PIAZZA PONTIDA IBAN:
IT 37 U 05034 11102 000
000 020624 NEON LUX
PUBBLICITA' Srl Via Borgo
Palazzo, 102 - 24125
BERGAMO (BG)
0,00 22,00 % 0,00 EUR
Imponibile 9 257,66 EUR
Importo dell'imposta 2 017,99 EUR
Totale imponibile 9 257,66 EUR
Totale documento 11 275,65 EUR
Importo pagamento 11 275,65 EUR
Riepilogo fiscale
Codice IVA Natura/Esenzione dell'IVA Imponibile Aliquota d'Imposta Importo dell'imposta
VAT 9 172,66 EUR 22,00 % 2 017,99 EUR
N1 Escluso art. 15 DPR 633/72 85,00 EUR 0,00 % 0,00 EUR
NEON LUX PUBBLICITA' SRL
VIA BORGO PALAZZO 102
IT 24125 Bergamo
BG
035214119
info@neonluxbergamo.it
Partita IVA
IT03624680165
Codice fiscale
03624680165
Numero REA
03624680165
IBAN
IT37U0503411102000000020624
Generated by
"""
from datetime import date


class LineItem(BaseModel):
    description: Optional[str]
    quantity: Optional[float]
    unit_price: Optional[float]
    amount: Optional[float]


class Invoice(BaseModel):
    invoice_number: Optional[str] = Field(description="invoice number")
    # invoice_date: Optional[str]
    invoice_date: Optional[str] = Field(description="Invoice Date")
    language: Optional[str] = Field(default=None, description="the language of invoice")

    # due_date: Optional[str]
    due_date: Optional[str] = Field(description="the due date of invoice")
    vendor_name: Optional[str]  =  Field(description="vendor name")
    # vendor_tax: Optional[str] = Field(description="vendor tax number")

    # vendor_number: Optional[str]  =  Field(description="vendor number")
    customer_name: Optional[str] = Field(description="customer name. e.g Mascot")
    currency: Optional[str]  = Field(description="currency")
    payment_terms: Optional[str] = Field(description="payment term")

    subtotal: Optional[float] = Field(description="Pre-tax invoice total — sum of line items before VAT")
    tax_rate: Optional[float] = Field(description="Tax rate")
    tax_amount: Optional[float] = Field(description="Total VAT charged on the invoice")
    total: Optional[float] = Field(description="Final invoice total — net_total plus vat_amount")
    confidence: float = Field(default=0.1 ,description="Confidence score of the extraction between 0.0 and 1.0.", ge=0.0, le=1.0)


model_dict = {
    1: 'granite4.1:3b',
    # 2: 'granite4:tiny-h',
    # 3: 'ibm/granite4:latest',
    # 4: 'gemma3:latest',
    # 5: 'gemma4:e2b',
    # 6: 'granite4.1:8b',
    7: 'ministral-3:3b',
    # 8: 'ministral-3',
    # 9: 'qwen3.5:4b',
}


SYSTEM_PROMPT = """
You are a financial invoice extraction agent.
Follow the schema documentation exactly.

You MUST follow rules strictly
- Never guess or hallucinate
- If a value is missing, return null
- Output MUST be valid JSON matching schema
- Numbers must be numeric (no commas, no currency symbols)
- Customer party NAME MUST contain "Mascot" 0r "mascot" or "MASCOT"
- Vendor party NAME MUST NOT contain "Mascot" or "mascot" or "MASCOT"
"""


INSTRUCTIONS = """
you are an expert for invoice extraction. please extract invoice from provided text!

you MUST follow the rules strictly:

#Document scanning:
- Search from top to bottom AND bottom to top
- Vendor info may be located: at top header OR at bottom/footer (company/legal section, signature block)

#Customer:
- Customer  MUST contain "Mascot" 0r "mascot" or "MASCOT"
- if not, set Customer = undefined

#Vendor
- Vendor MUST not contain "Mascot" 0r "mascot" or "MASCOT
- if "mascot" found in vendor section, it is okey to inteprete it as customer name  
- You have to yse the `get_vendor_number' to verify vendor.        

"""


# llm_model = model_dict[1]
# print(llm_model)

# 1. Define the desired output structure (Pydantic validation)
class AgentResponse(BaseModel):
    summary: str
    action_taken: bool


def run_agent(llm_model):
    try:
        # 2. Configure Pydantic AI to use a local Granite endpoint (e.g., via Ollama on port 11434)
        model = OpenAIChatModel(
            llm_model, # or your specific Granite tag
            provider=OllamaProvider(
                base_url='http://localhost:11434/v1/',
                api_key='ollama' # Local endpoint doesn't strictly need a real key
            )
        )

        # 3. Initialize the Agent
        agent = Agent(
            model,
            output_type=Invoice,
            # system_prompt=SYSTEM_PROMPT,
            instructions=INSTRUCTIONS
        )

        @agent.tool
        def get_vendor_number(ctx: RunContext[str],question:str) -> str:
            """Get vendor number"""
            return asyncio.run(fetch_data(question))


        # 4. Run the Agent
        result = agent.run_sync(f"<text>{u_prompt}</text>")
        # print(result.all_messages())
        print(result.output)

    except ValidationError as exc:
        missing_fields = [
            error["loc"][0]
            for error in exc.errors()
            if error["type"] == "missing"
        ]

        print("Missing fields:", missing_fields)
        # Output: Missing fields: ['name', 'email']

for k,v in model_dict.items():

    print (f"Model: {v}")
    print(f">>>>>>> Running. Please wait.....")
    start = time.time()
    run_agent(v)
    end = time.time()
    print(f"=>>>>>> Execution time: {end - start:.6f} seconds")
    print(f"---------------------------------------------------")
    # Filter and extract the names of all missing fields
